### ISSUE TITLE
[FEATURE] Santise input of `brickflow_internal_only_run_tasks` parameter

### ISSUE THREAD

**Issue by maxim-mityutko** [Nike-Inc/brickflow#105]
**Is your feature request related to a problem? Please describe.**
This parameter expects coma delimited list of tasks that should be executed. I noticed that on multiple occasions engineers provide this list with (a) trailing space after coma, e.g `task_1, task_2`; (b) in python list form, e.g. `['task_1', 'task_2']`

**Cloud Information**

- [x] AWS
- [x] Azure
- [x] GCP
- [x] Other

**Describe the solution you'd like**
Cleanup the input while parsing the contents of `brickflow_internal_only_run_tasks` parameter:
- trim entries
- check if value starts and ends with '[' and ']' and do `json.loads`

Feels like https://github.com/Nike-Inc/brickflow/blob/b07ebfb88517d03dc0191cf587a84b7e6e54b82d/brickflow/engine/task.py#L677-L690 is the logical place for this.

**Describe alternatives you've considered**
Educating users is always an option.

**Additional context**

**Comment by asingamaneni** [comment]
This is a good idea and needed.
