### ISSUE TITLE
[FEATURE] Support '.yaml' extension for .brickflow-project-root.yml and brickflow-multi-project.yml files.

### ISSUE THREAD

**Issue by menathan** [Nike-Inc/brickflow#150]
**Is your feature request related to a problem? Please describe.**
Support '.yaml' extension for .brickflow-project-root.yml and brickflow-multi-project.yml files.

**Cloud Information**
N/A

**Describe the solution you'd like**
Besides '.yml' also support '.yaml' file extensions for mentioned files.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by pariksheet** [comment]
assigned it to Iacomini.riccardo@gmail.com
