### ISSUE TITLE
[FEATURE] Enable DBR 15.4 LTS support 

### ISSUE THREAD

**Issue by boggavarapu** [Nike-Inc/brickflow#152]
**Is your feature request related to a problem? Please describe.**
Enable DBR 15.4 LTS support 

**Cloud Information**

- [X ] AWS
- [ ] Azure
- [ ] GCP
- [ ] Other

**Describe the solution you'd like**
when using workflows unable to spin up a DBR 15.4 LTS resources

**Comment by asingamaneni** [comment]
#161 solved this
