### ISSUE TITLE
[FEATURE] Option to deploy workflows in either `PAUSED`|`UNPAUSED`

### ISSUE THREAD

**Issue by AlecVivian** [Nike-Inc/brickflow#39]
**Is your feature request related to a problem? Please describe.**
As a deploying engineer, I want to have control over the run state of a new workflow, rather than allowing the job to assume schedule on publish.

**Cloud Information**

- [ x] AWS
- [ x] Azure
- [x ] GCP
- [x ] Other

**Describe the solution you'd like**
On deployment, I would like to specify the state of the workflow as it's published to Databricks. This is to accommodate a `trust but verify` approach to higher environment deployments, where an engineer can validate the state of the workflow prior to setting the workflow to UNPAUSED state.

**Describe alternatives you've considered**
I have a custom deployments tool that accommodates this status configuration. Additionally, I see that the pydantic models in `brickflow.bundles.model` acknowledge that scheduling state is configurable.

**Comment by asingamaneni** [comment]
I will start working on this and we will have it in next release!

**Comment by asingamaneni** [comment]
@AlecVivian I have create the pr #42 , You can test it directly before it is merged by following the below steps.

Install brickflows using the command below
`pip install git+ssh://git@github.com/nike-inc/brickflow.git@feature-support-job-schedule-pause-status`

Change `brickflow_version: auto` -> `brickflow_version: feature-support-job-schedule-pause-status` in `.brickflow-project-root.yml`
