### ISSUE TITLE
[QUESTION/FEATURE] (If within scope of project) Provide further documentation of leveraging Brickflow for triggering workflow deployments outside of Databricks

### ISSUE THREAD

**Issue by AlecVivian** [Nike-Inc/brickflow#45]
**Is your feature request related to a problem? Please describe.**
Reading through the project, it appears that Workflow deployments are preferred for execution within Databricks environment (phrasing of docs/highlevel.md - `...help deploy and manage workflows *in* Databricks.`). Would like to leverage this framework to handle deployments coming from an execution environment such as Github Actions/another Serverless execution function(?).

**Cloud Information**

- [ ] AWS
- [ ] Azure
- [ ] GCP
- [ x ] Other

**Describe the solution you'd like**
To fit the mantra of code/git first deployments, it would be helpful to further elaborate on deployments __outside__ of the Databricks environment (leveraging GitHub Actions to handle deploys less state-dependent on the compute engine, and more state-dependent of the generated workflows). 

**IF** deployments leveraging such an external compute environment are achievable, further documenting deployment execution with this framework will greatly improve onboarding for interested end-users.

**Describe alternatives you've considered & Additional context**
I am currently using a YAML configuration framework that determines deployment go/no-go for projects by leveraging process-generated tags on workflow object, which look for whether or not the tag in the workflow's repo configuration matches the tag tied to the active workflow in Databricks (if tags match, skip deployment of the workflow. If tags are different, deploy workflow by overwriting the existing workflow in Databricks). Because the evaluation happens at runtime, there is no additional state capture required as the versions are captured in-code.

^^ REASON FOR CASE SUMMARY: I want to know if I can employ this framework in a similar manner to the above situation, where configurations happen outside of Databricks and deployment state details captured in name/tags of the active workflow can drive new workflow creation/updates/deletions. 

**Additional context**
This is more of a question ticket for the project as much as it is a feature request. Am looking to understand whether or not it is feasible to employ this framework as the engine for our workflows given the criteria it needs to meet for my use case.

**Comment by asingamaneni** [comment]
@AlecVivian I think what we meant in the documentation is brickflow is used to manage workflows which exists in Databricks. But essentially Brickflow is a library which has a cli through we do the deployments and manage workflows.
So the cli can be run any where, be it jenkins or github-actions or docker container etc. As long as you have your Databricks token configured, you should be good.

**Comment by asingamaneni** [comment]
@AlecVivian if you still feel that the question is not answered, please re-open the ticket
