### ISSUE TITLE
[BUG] `-w` option from `bf projects deploy` is missing in version 0.10 and up

### ISSUE THREAD

**Issue by emulanob** [Nike-Inc/brickflow#47]
**Describe the bug**
Since version 0.10.0 the command `bf projects deploy` doesn't have the `-w` flag used to specify a single workflow name.
It's also not mentioned in the docs.

**To Reproduce**
1. `bf projects deploy -w myworkflow.py`
```
Error: No such option: -w
```

**Expected behavior**
Should deploy that single workflow "myworkflow.py"

**Comment by asingamaneni** [comment]
We want to enable this option only for: --env local.

If there are 3 workflows already existing in the Databricks remote, then if we use -w and deploy a new workflow - we are anticipating that the 3 workflows which were already deployed should not be deleted.

**Comment by BrendBraeckmans** [comment]
@asingamaneni I also have a CI/CD use case for the `-w` and `-wd` options as mentioned on Slack.

> 
We want to enable this option only for: --env local.
> 

Is above a hard requirement as we would need to deploy a single workflow to our different environments in this CI/CD use case ... ?

**Comment by asingamaneni** [comment]
We would not want to deploy single workflows via CI/CD as that would require us to maintain and manage the state other than what DAB provides us. Want this option only for local, as we wouldn't want engineers to deploy all the workflows which have schedule and increase the cost.

**Comment by BrendBraeckmans** [comment]
Ok clear we'll find a way to achieve what we need with only the local env deploy.
Thanks for the clear and swift reply :)
