### ISSUE TITLE
Support for Task Run as Job

### ISSUE THREAD

**Issue by stikkireddy** [Nike-Inc/brickflow#7]
Task Type is: run_job_task

If run_job_task, indicates that this task must execute another job.

https://docs.databricks.com/api/workspace/jobs/create

Job managed by brickflow
```
wf = Workflow(...)

@wf.job_task
def run_job():
    from some_some_folder import wf
    return wf
```

Jobs not managed by brickflow
```
wf = Workflow(...)

@wf.job_task
def run_job():
    return Workflows.from_name("...")
```

**Comment by asingamaneni** [comment]
Duplicate of #55, so closing this!
