### ISSUE TITLE
[FEATURE] Add support for cerberus and other credential stores in snowflake operator

### ISSUE THREAD

**Issue by ckonuganti** [Nike-Inc/brickflow#70]
**Is your feature request related to a problem? Please describe.**
Current implementation of snowflake operator supports databricks secrets only. We have a need to use other credential stores like cerberus. 

**Cloud Information**

- [ ] AWS
- [ ] Azure
- [ ] GCP
- [ ] Other

**Describe the solution you'd like**
Enhance the snowflake operator logic to support other credential stores along with databricks secrets.

**Comment by asingamaneni** [comment]
Cerberus is not opensource anymore, hence it has to be an internal implementation!
