### ISSUE TITLE
[BUG] UcToSnowflakeOperator throws Incorrect Username and Password error

### ISSUE THREAD

**Issue by rebecca-rajshree** [Nike-Inc/brickflow#85]
**Describe the bug**
UcToSnowflakeOperator throws Incorrect Username and Password error even though correct credentials are provided in databricks secrets. I assume the okta authentication is not being done when load_type is given as "full".
Another thing I came across - Eventhough the load_type provided is "full", it still asks for the incremental_filter to be filled.

**To Reproduce**
Provide all necessary parameters for the UcToSnowflakeOperator along with authenticator and load_type = "full".

**Expected behavior**
The authentication process should work when load_type = "full" and authenticator parameter is provided.

**Screenshots**

**Cloud Information**

- [ ] AWS
- [ ] Azure
- [ ] GCP
- [ ] Other

**Desktop (please complete the following information):**

**Additional context**

**Comment by ckonuganti** [comment]
Looking into this issue
