### ISSUE TITLE
[BUG] Transitive dependency on `pydantic < 2.0.0` due to `snowflake==0.5.1`

### ISSUE THREAD

**Issue by maxim-mityutko** [Nike-Inc/brickflow#95]
**Describe the bug**
`snowflake==0.5.1` has a transitive dependency on `pydantic < 2.0.0`. The `snowflake` dependency is always required if plugins functionality is enabled. Hence Brickflow usage is limited to the cases when no extra dependencies are required or if said dependencies does not require `pydantic >= 2.0.0`

**To Reproduce**
View `snowflake` package dependencies.

**Expected behavior**
Compatibility with `pydantic >= 2.0.0`

**Screenshots**
```
snowflake==0.5.1
├── snowflake-core [required: ==0.5.1, installed: 0.5.1]
│   ├── atpublic [required: >=4, installed: 4.0]
│   ├── pydantic [required: >=1.10.7,<2.0.0, installed: 1.10.13]
│   │   └── typing-extensions [required: >=4.2.0, installed: 4.9.0]
```

**Cloud Information**

- [x] AWS
- [x] Azure
- [x] GCP
- [ ] Other

**Desktop (please complete the following information):**

**Comment by asingamaneni** [comment]
can I close this, as we will be working on this in #93 ?

**Comment by maxim-mityutko** [comment]
I think so, it is mentioned in the other issue anyways. So the paper trail is there.

**Comment by maxim-mityutko** [comment]
This can be resolved by:
1. Bump `snowflake` dependency version to `0.6.0` in project dependencies.
2. Bump the Airflow version to at least `2.7.3` in project dependencies.
3. Update versions in: https://github.com/Nike-Inc/brickflow/blob/6ba515b9eb291195089fd54ea701cfcb0cd97838/brickflow/engine/task.py#L823-L825

**Comment by asingamaneni** [comment]
@maxim-mityutko thanks for the solution, can you please raise the PR for the same and also update the `pyproject.toml` file!
